- hyperparam_set:
    batch_norm: 'on'
    batch_size: 64
    data_aug_cutout_size: 5
    max_learning_rate: 0.4
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 64
    data_aug_cutout_size: 5
    max_learning_rate: 0.4
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 128
    data_aug_cutout_size: 5
    max_learning_rate: 0.4
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 128
    data_aug_cutout_size: 5
    max_learning_rate: 0.4
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 64
    data_aug_cutout_size: 5
    max_learning_rate: 0.6
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 64
    data_aug_cutout_size: 5
    max_learning_rate: 0.6
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 128
    data_aug_cutout_size: 5
    max_learning_rate: 0.6
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 128
    data_aug_cutout_size: 5
    max_learning_rate: 0.6
    momentum: 0.99
